# Generated by Django 5.0.6 on 2024-07-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviezapp', '0002_alter_movie_actors_alter_movie_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ImdbRating',
            field=models.FloatField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ImdbVotes',
            field=models.IntegerField(default='N/A'),
        ),
    ]
