# Generated by Django 5.0.6 on 2024-07-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviezapp', '0003_alter_movie_imdbrating_alter_movie_imdbvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ImdbRating',
            field=models.CharField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ImdbVotes',
            field=models.CharField(default='N/A'),
        ),
    ]
