# Generated by Django 5.0.6 on 2024-07-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviezapp', '0004_alter_movie_imdbrating_alter_movie_imdbvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Year',
            field=models.CharField(default='N/A'),
        ),
    ]
